dist: xenial
addons:
  chrome: stable
language: node_js
install:
- npm ci
- npm run webdriver:update
cache:
  directories:
  - node_modules
env:
  global:
  - secure: pPARQWg3OIQFyUcDmtbNSpLZxEZ+hXYyEOF1G+cqQWBWfeceVHOBQN9XG1CkjNodpnByHIREPCtBX1kv5L3Of0Wp09N6nDVjm0+bG2I8IeXYSwJC1eHTQ/A4wCSyg/yQfbsR8637e095WsKrShpbd6Uo6J3s9YnYelbu5O0g06cCiWLxjZyx6eFWHbJKhdpdizO7K/haScmzAlor2ieDIZvDdd8m1lv19E/HQFLJ36ZU+ENNHZ9mhzNjMm8zr3jdAGW24Z3l1d+ioeVaUL9+p3MporYiHqFaPGlRFkCsoD51W7kb5usyhySjldynnrJsZk3Izxpn18i3SD9dxqO8tVzWdiKPXMZwQ0guMyYx/WhlFurUei20TlneIlxRRo9Mzvpr1N92txvtm2r7tb0fuGs+Va2YREwOecSXytJMtp2KYeZd9bA60Sz4aMMGqFGoWAIeZeEUAzIdsKVoB7Y54IIVFFbrK6F/wHY8RWYiA3bujDBq/c+fFLUYSkWkwj0WIEW+3Eid8LcjdajPErs7dyfXm9c+NOkLzcWmaC+0af8aM7I6Qak1+1Q1B2waMhuM4e9QRc9v2xEine7+JOyIFQK0H7KtxAe1yJ5ff+74DB9cFsnHjoCBESxuS1dPlIE5oG5H0CbAoV+UNMrQLTVSw9jL9TDUDV0LIP4D2cGh5P8=
  - secure: WNlXi2heOMF/bzLvqMB97vioAzo3RU1cdpkXLs2FG6soyc/D4vJKJvrmJLJuR1etW/+0gRI9jBzF0qVZ1am1DLrSENTw+CFG9yOTKsluWrXgp5/SdpEb9v2B/oXg/4h2Y0w9nw64FUtITCocRMsQBzaloUPlKnuntLiO7LWfLgvBh0d4QZ2odYvm2gExTGjWqhXmo0M96gWCBpWXqRD2qKjLThnBcOuVMFOUTQGpa2UCjOJgCUkFbHP/n0wwQjSOSVDGEVEwLQX4DbZeTJKBXBof503xu6iKsLqswusIBmh/JfPc8VjSP5gyhput6tjLEi9R9BUc5fPQCMQuH4UbpZ+jOUgoYwnm7cFMOosz9TabvxbtPmh3xx9QzlsEDr5A8G9E5I1GSWokvEGXBGfaDPe2b6ljsjorso1lrdoqQ707G9OUwTrd2GfGTSAARTeWo9BZnGKHzKh9wFqu4vs5nl/+VNN0adj9eVUwA5vDBZ0w5NmGTGbGmJSU5588MlVVWAmC5tweVEvRRg+nuMKb2sv9JdP4f6d0FUWsMiE9ovcTtDEmKGw+Ovm07lqPSAnIBEWGqsrA45zawrVzwUbKbYo3Ucx0RF32XGBlNRBCbltivLOqaZ5eaqApxYHosI/tA2JArpgZlVG3Uv9+/M7QPa6KaypEWsEu9gXl5AEEnx0=
